### ISSUE TITLE
ScalarBaseMult returns 255-bit value

### ISSUE THREAD

**Issue by Kleshni** [Yawning/libelligator#1]
The original [paper](http://elligator.cr.yp.to/elligator-20130828.pdf) states, that representative value must be floor(log2(q)) bits long. For q = 2 ^ 255 - 19 it means, that `ScalarBaseMult` should return 254 bits.

But current implementation returns 32 bytes with only one MSB always unset. It's because current square root function can return either the greatest or the least of two existing roots. One of them is greater than (p - 1) / 2, and thus can occupy 255 bits, while the least root is always 254 bits long.

The paper proposes to use the least root. [This](https://github.com/DeDiS/crypto/blob/master/edwards/el2.go#L103-L105) Go implementation does so.

Extra bit makes a key more detectable. If a root, calculated with the same function, of a squared representative doesn't match the original, then attacker can say, that it doesn't encode a key.

**Comment by Yawning** [comment]
I shall look into this when I have time (though I've been quite busy lately).  The main things I want to establish are, "did I screw up when porting agl's code to C++" and "if not, should I care about being backward compatible with agl's code".

Nice catch, and this probably makes my life interesting if agl's implementation has the same issue since I use his code for obfs4....

**Comment by Yawning** [comment]
I opened a pull request upstream to fix this there a while ago but haven't gotten around to addressing it here till now.  It's fixed, thanks.
